//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunchOrder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbmealsEntities : DbContext
    {
        public dbmealsEntities()
            : base("name=dbmealsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MEAL_GROUPS> MEAL_GROUPS { get; set; }
        public virtual DbSet<MEAL> MEALS { get; set; }
        public virtual DbSet<ORDER_ITEMS> ORDER_ITEMS { get; set; }
        public virtual DbSet<ORDER> ORDERS { get; set; }
    }
}
