//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunchOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEAL_GROUPS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEAL_GROUPS()
        {
            this.MEAL_GROUPS1 = new HashSet<MEAL_GROUPS>();
            this.MEALS = new HashSet<MEAL>();
        }
    
        public long ID { get; set; }
        public string NAME { get; set; }
        public Nullable<long> FK_MEAL_GROUP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEAL_GROUPS> MEAL_GROUPS1 { get; set; }
        public virtual MEAL_GROUPS MEAL_GROUPS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEAL> MEALS { get; set; }
    }
}
