//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunchOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEAL
    {
        public long ID { get; set; }
        public string NAME { get; set; }
        public double PRICE { get; set; }
        public long FK_MEAL_GROUP { get; set; }
    
        public virtual MEAL_GROUPS MEAL_GROUPS { get; set; }
    }
}
