//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunchOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_ITEMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER_ITEMS()
        {
            this.ORDER_ITEMS1 = new HashSet<ORDER_ITEMS>();
        }
    
        public long ID { get; set; }
        public string NAME { get; set; }
        public double PRICE { get; set; }
        public Nullable<long> FK_ORDER_ITEMS { get; set; }
        public long FK_ORDERS { get; set; }
    
        public virtual ORDER ORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_ITEMS> ORDER_ITEMS1 { get; set; }
        public virtual ORDER_ITEMS ORDER_ITEMS2 { get; set; }
    }
}
